package com.pharmacy.enums;

public enum Message {
	
	MAIL_ID_EXIST,
	USERNAME_EXIST,
	MOBILENUMBER_EXIST,
	PROCEED,
	DELETED_SUCCESSFULL,
	UNSUCCESSFULL,
	DATABASE_ERROR,
	UNABLE_TO_FETCH_FROM_DATBASE,
	SAME_DATA_EXIST,
	DATA_NOT_UPDATED

}